# Generated by Django 2.2.7 on 2019-11-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('publishedDate', models.CharField(max_length=15)),
                ('type10', models.CharField(max_length=10)),
                ('identifier10', models.CharField(max_length=20)),
                ('type13', models.CharField(max_length=10)),
                ('identifier13', models.CharField(max_length=20)),
                ('pageCount', models.CharField(blank=True, max_length=10, null=True)),
                ('smallThumbnail', models.URLField()),
                ('thumbnail', models.URLField()),
                ('language', models.CharField(max_length=10)),
            ],
        ),
    ]
