# Generated by Django 2.2.7 on 2019-11-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='defoult',
            field=models.CharField(default='defi', max_length=10),
        ),
    ]
